os:
  - linux
  - osx
language: generic
env:
  global:
  - SWIFT_VERSION=5.0

sudo: required

dist: trusty

osx_image: xcode10.4

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(cat ./install-swiftenv.sh)";
      sudo apt-get install -y libcurl4-openssl-dev libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev libbsd-dev;
      sudo rm /usr/bin/ld && sudo ln -s /usr/bin/ld.gold /usr/bin/ld;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gem install slather;
    fi
  - git --version

script:
  - swift package resolve # clones all dependencies
  - swift build # build project
  - swift test #run tests

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift package generate-xcodeproj;
      slather setup BluemixObjectStorage.xcodeproj;
      xcodebuild -project BluemixObjectStorage.xcodeproj -scheme BluemixObjectStorage build;
      xcodebuild -project BluemixObjectStorage.xcodeproj -scheme BluemixObjectStorage -enableCodeCoverage YES test;
      slather coverage --coveralls --binary-basename BluemixObjectStorage.framework -v;
    fi
